###############################################################
#                 Authetlia Configuration                     #
###############################################################

# Create Secrets Folder
# mkdir ~/docker/secrets
# sudo chown root:root ~/docker/secrets
# sudo chmod 600 ~/docker/secrets
# su
# cd ~/docker/secrets
# nano authelia_jwt_secret
# Define in secrets section of docker

host: 0.0.0.0
port: 9091
log_level: warn

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.willishomeserver.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

access_control:
  default_policy: deny
  rules:
    - domain: authelia.willishomeserver.com
      policy: bypass
    - domain:
        - "*.willishomeserver.com"
        - "willishomeserver.com"
      policy: two_factor
    - domain:
        - "*.willishomeserver.com"
        - "willishomeserver.com"
      policy: bypass
      networks:
        - 27.124.106.233

session:
  name: authelia_session 
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600
  inactivity: 300
  domain: willishomeserver.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt
