[http.routers]
	[http.routers.freenas-rtr]
      entryPoints = ["https"]
      rule = "Host(`nas.willishomeserver.com`)"
      service = "freenas-svc"
      middlewares = ["chain-oauth"]
      [http.routers.freenas-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.freenas-svc]
    [http.services.freenas-svc.loadBalancer]
      passHostHeader = true
      [[http.services.freenas-svc.loadBalancer.servers]]
        url = "http://10.1.1.191:80" # or whatever your external host's IP:port is
