[http.routers]
	[http.routers.ssh-rtr]
      entryPoints = ["https"]
      rule = "Host(`ssh.willishomeserver.com`)"
      service = "ssh-svc"
      [http.routers.ssh-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.ssh-svc]
    [http.services.ssh-svc.loadBalancer]
      passHostHeader = true
      [[http.services.ssh-svc.loadBalancer.servers]]
        address = "10.1.1.141:22"
